#!/bin/bash
# duhsc: simple way to figure out space usage in a directory

if [[ -z $1 ]]; then
	if [[ "$HOME" == $(pwd) ]]; then
		du -hsc .config .local .cache * | sort -h | grep -v '^0\s'
	else
		du -hsc * | sort -h | grep -v '^0\s'
	fi
else
	du -hsc "$@" | sort -h
fi

