#!/bin/bash
# duhsc: simple way to figure out space usage in a directory

if [[ -z $1 ]]; then
	find ./ -mindepth 1 -maxdepth 1 -print0 | xargs -0 du --si -sc | \
		sort -h | grep -v '^0\s'
else
	du --si -sc "$@" | sort -h
fi

