#!/bin/bash
# gdd: quickly compile a D program (poorly hacky script)
#   automatically links against curl if it looks like that is needed
#   does not compile if there is already an executable newer than main

main="${1-main}"
main="${main/%.d/}"
if [[ ! -f "$main.d" ]]; then
	echo "Main file does not exist"
	if [[ -z "$1" ]]; then
		echo "[You didn't specify one, so we assumed main.d]"
	fi
	exit 1
fi
shift

LDFLAGS=
if [[ -n "$(cat $main.d | perl -ne '
		if(m/^\s*import\s+([^;]*\s*,\s*)*etc.c.curl(\s*,\s*+[^;]*)?\s*;/) {
			print"$_";
		}')" ]]; then
	LDFLAGS="${LDFLAGS} -L-lcurl -L-lssl"
fi

if [[ "$main.d" -nt "$main" ]]; then
	gdmd $main.d -g -pipe -O -w -wi ${LDFLAGS} $@
	[[ -f "a.out" ]] && mv a.out $main
	[[ -f "$main.o" ]] && rm $main.o
fi

