#!/bin/bash
# git-pall: "git pall" pushes to both my VPS and github at the same time

declare -A rMap
rMap[".config"]="conf-$(hostname)"

declare -A users
users["jail"]="CodeBlock"

repo="${1-$(basename $(pwd))}"

if [[ -n "${rMap[$repo]}" ]]; then
	repo="${rMap[$repo]}"
fi

git push "git@jachapmanii.net:$repo"

if [[ -z "${users[$repo]}" ]]; then
	git push "git@github.com:JAChapmanII/$repo"
else
	git push "git@github.com:${users[$repo]}/$repo"
fi

wait

