#!/bin/bash
# git-tall: "git tall" pushes tags to both my VPS and github at the same time

declare -A rMap
rMap[".config"]="conf-$(hostname)"

declare -A users

declare -A ghMap
ghMap["jail"]="Jail"

repo="${1-$(basename $(pwd))}"

if [[ -n "${rMap[$repo]}" ]]; then
	repo="${rMap[$repo]}"
fi

git push --tags "git@jachapmanii.net:$repo"

if [[ -n "${ghMap[$repo]}" ]]; then
	repo="${ghMap[$repo]}"
fi

if [[ -z "${users[$repo]}" ]]; then
	git push --tags "git@github.com:JAChapmanII/$repo"
else
	git push --tags "git@github.com:${users[$repo]}/$repo"
fi

wait

